<?php

namespace App\Http\Traits\Parsers;

Trait ViewEdit
{
 
    public function view_edit()
    {
        
        $start_time = microtime(true);
        
        $table   = $this->table;
        
        $data    = "";
        
        $data   .= $this->view_edit_start();
        
        $data   .= $this->view_edit_form_elements();
        
        $data   .= $this->view_edit_end();
        
        file_write(base_path().'/resources/views/admin/'.$table.'/edit.blade.php', $data);
        
        $end_time = microtime(true);
        
        return "edit view created in ". ( $end_time - $start_time ) ." s";
        
    }
    
    
    private function view_edit_start()
    {
        
        $model = $this->model;
        
        $controller = $this->controller;
        
        $data = "@extends('admin.layout')

@section('title')Modify ".str_replace('_',' ',$model)." @stop

@section('main')

<main class=\"column is-12-desktop is-12-mobile padding-top-10 padding-bottom-20 columns is-multiline\" >

    <!--Generated by Functions-->
    <section class=\"column is-12 padding-0\">{!! breadcrumb('$controller', $". strtolower($model) ."->id) !!}</section>
    
    <section class=\"column is-12 padding-0\">
    
        <h1 class=\"title is-3\">Edit ". strtolower(str_replace('_',' ',$model)) ."</h1>
    
    </section>
    
    <section class=\"column is-12 padding-0\">{!! errors(\$errors) !!}</section>
    
    <section class=\"column is-12 padding-0 margin-top-30\">
    
        {!! Form::open( ['url'=> action('$controller@update', $". strtolower($model) ."->id), 'method'=>'PATCH', 'enctype'=>'multipart/form-data' ]) !!}

        ";
        
        return $data;
        
    }
    
    
    private function view_edit_end()
    {
        
        $model = $this->model;
        
        $data = "
        <div class=\"field is-grouped\">
            <div class=\"control is-expanded\">
                <button class=\"button is-success is-fullwidth\" type=\"submit\">Save</button>
            </div>
        </div>
    
    {!! Form::close() !!}


    </section>

</main>

@stop
        ";
        
        return $data;
        
    }
    
    
    private function view_edit_form_elements()
    {
        
        $data = "";
        
        $model = $this->model;
        
        $instance = strtolower($model);
        
        foreach( (array) $this->columns as $column)
        {
        
            if( ! in_array($column, ['created_at', 'updated_at', 'id']) )
            {
                
                if( ends_with($column, '_id') ){
                        
                    $data .= "
                    
                <div class=\"field is-horizontal has-addons\">
                
                    <div class=\"field-label is-normal\">
                        <label class=\"label has-text-left\">".str_replace('_',' ',ucfirst( substr( $column, 0, -3 ) ))."</label>
                    </div>
                    
                    <div class=\"field-body\">
                        <div class=\"field\">
                            <div class=\"control\">
                                <span class=\"select\">
                                    {!! Form::select('$column', \App\\$model::pluck('name', 'id'), \$".$instance."->$column , ['class'=>'select2']) !!}
                                </span>
                            </div>
                        </div>
                    </div>
                    
                </div>
                    
                    ";
                        
                } elseif( starts_with($column, 'is_') ){
                    
                $data .= "
                
                <div class=\"field is-horizontal has-addons\">
                
                    <div class=\"field-label is-normal\">
                        <label class=\"label has-text-left\">".str_replace('_',' ',ucfirst( $column ))."</label>
                    </div>
                    
                    <div class=\"field-body\">
                        <div class=\"field\">
                            <div class=\"control\">
                                <span class=\"select\">
                                    {!! Form::select('$column', [ ''=>'-Select-','1'=>'Yes', '0'=>'No'], \$".$instance."->$column) !!}
                                </span>
                            </div>
                        </div>
                    </div>
                    
                </div>
                
                ";
                
                } elseif( ends_with($column, '_date') ){
                        
                    $data .= "
                <div class=\"field is-horizontal has-addons\">
                
                    <div class=\"field-label is-normal\">
                        <label class=\"label has-text-left\">".str_replace('_',' ',ucfirst($column))."</label>
                    </div>
                    
                    <div class=\"field-body\">
                        <div class=\"field\">
                            <div class=\"control\">
                                {!! Form::text('$column', \$".$instance."->$column , ['class'=>'input datepicker']) !!}
                            </div>
                        </div>
                    </div>
                    
                </div>
                
                    ";
                    
                } elseif( ends_with($column, '_time') ){
                        
                    $data .= "
                
                <div class=\"field is-horizontal has-addons\">
                
                    <div class=\"field-label is-normal\">
                        <label class=\"label has-text-left\">".str_replace('_',' ',ucfirst($column))."</label>
                    </div>
                    
                    <div class=\"field-body\">
                        <div class=\"field\">
                            <div class=\"control\">
                                {!! Form::text('$column', \$".$instance."->$column , ['class'=>'input timepicker']) !!}
                            </div>
                        </div>
                    </div>
                    
                </div>    
                
                    ";
                    
                } elseif( ends_with($column, '_photo') || ends_with($column, '_file') ){
                    
                    $file_column = $column."s";
                    $data .= "
                <div class=\"field is-horizontal has-addons\">
                
                    <div class=\"field-label is-normal\">
                        <label class=\"label has-text-left\">".str_replace('_',' ',ucfirst($column)).": </label>
                        <label class=\"label has-text-left\">
                            <span class=\"badge badge-primary\"><input type=\"checkbox\" value=\"1\" name=\"".$column."_delete\" /> remove old file</span>
                        </label>
                    </div>
                    
                    <div class=\"field-body\">
                        <div class=\"field\">
                            <div class=\"control\">
                                {!! Form::file('$file_column' , ['class'=>'file']) !!}
                            </div>
                        </div>
                    </div>
                    
                </div>  
                    ";
                    
                } elseif( ends_with($column, '_images') ){
                    
                    $file_column = $column;
                    $data .= "
                <div class=\"form-group\">
                    
                    @if( is_array(\$".strtolower($model)."->$file_column) && count(\$".strtolower($model)."->$file_column) > 0)
                    <h4>Select previous ".str_replace('_',' ',$file_column)." to remove</h4>
                    <div class=\"gallery\">
                    @foreach(\$".strtolower($model)."->$file_column as \$image)
                    <a class=\"gallery-item\" href=\"{{\$image}}\" title=\"Image\" data-gallery>
                        <div class=\"image\">
                            {!! xs(\$image) !!}
                            <ul class=\"gallery-item-controls\">
                                <li><label class=\"check\"><input type=\"checkbox\" class=\"\" value=\"{{\$image}}\" name=\"".$column."_delete[]\" /></label></li>
                            </ul>                                                                    
                        </div>
                    </a>
                    @endforeach
                    </div>
                    @endif
                    <label for=\"".substr($file_column, 0, -1)."[]\"><span class=\"badge badge-primary\">Add ".str_replace('_',' ', $file_column)."</span></label>
                    {!! Form::file('".substr($file_column, 0, -1)."[]' , ['class'=>'form-control file', 'multiple'=> 'multiple']) !!}
                </div>
                    ";
                    
                } elseif( ends_with($column, '_files') ){
                    
                    $file_column = $column;
                    $data .= "
                <div class=\"form-group\">
                    @if( is_array(\$".strtolower($model)."->$file_column) && count(\$".strtolower($model)."->$file_column) > 0)
                    <h4>Select previous ".str_replace('_',' ',$file_column)." to remove</h4>
                    <ul class=\"list-group\">
                    @foreach(\$".strtolower($model)."->$file_column as \$file)
                    <li class=\"list-group-item\">
                        <input type=\"checkbox\" value=\"{{\$file}}\" name=\"".$column."_delete[]\" />
                        {{ucfirst(substr(\$file, -4))}} File
                    </li>
                    @endforeach
                    </ul>
                    @endif
                    <label for=\"".substr($file_column, 0, -1)."[]\"><span class=\"badge badge-primary\">Add ".str_replace('_', ' ', $file_column)."</span></label>
                    {!! Form::file('".substr($file_column, 0, -1)."[]' , ['class'=>'form-control file', 'multiple'=> 'multiple']) !!}
                </div>
                    ";
                    
                } elseif( ends_with($column, 'details') || ends_with($column, 'detail') ){
                    
                    $data .= "
                <div class=\"field is-horizontal\">
                    <div class=\"field-label is-normal\">
                        <label class=\"label has-text-left\">".str_replace('_',' ',ucfirst($column))."</label>
                    </div>
                    <div class=\"field-body\">
                        <div class=\"field\">
                            <div class=\"control\">
                                {!! Form::textarea('$column', \$".$instance."->$column , ['class'=>'textarea summernote']) !!}
                            </div>
                        </div>
                    </div>
                </div> 
                    ";
                } elseif($column != 'created_by' && $column != 'updated_by'){
                    
                    $data .= "
                <div class=\"field is-horizontal has-addons\">

                    <div class=\"field-label is-normal\">
                        <label class=\"label has-text-left\">".str_replace('_',' ',ucfirst($column))."</label>
                    </div>
                    
                    <div class=\"field-body\">
                        <div class=\"field\">
                            <div class=\"control\">
                                {!! Form::text('$column', \$".$instance."->$column , ['class'=>'input']) !!}
                            </div>
                        </div>
                    </div>
                    
                </div>  
                    ";
                    
                } 
        
            }
            
        }
        
        return $data;
        
    }
    
}