<?php

namespace App\Http\Traits\Parsers;

Trait ViewCreate
{
 
    public function view_create()
    {
        
        $start_time = microtime(true);
        
        $table   = $this->table;
        
        $data    = "";
        
        $data   .= $this->view_create_start();
        
        $data   .= $this->view_create_form_elements();
        
        $data   .= $this->view_create_end();
        
        file_write(base_path().'/resources/views/admin/'.$table.'/create.blade.php', $data);
        
        $end_time = microtime(true);
        
        return "create created in ". ( $end_time - $start_time ) ." s";
        
    }
    
    
    private function view_create_start()
    {
        
        $model = $this->model;
        
        $controller = $this->controller;
        
        $data = "
@extends('admin.layout')

@section('title') Add new ".str_replace('_',' ',$model)." @stop

@section('main')

<main class=\"column is-12-desktop is-12-mobile padding-top-10 padding-bottom-20 columns is-multiline\" >

    <!--Generated by Functions-->
    <section class=\"column is-12 padding-0\">{!! breadcrumb('$controller') !!}</section>
    
    <section class=\"column is-12 padding-0 margin-bottom-20\">

        <h1 class=\"title is-3\">Add new ". strtolower(str_replace('_',' ',$model)) ."</h1>

    </section>

    <section class=\"column is-12 padding-0\">{!! errors(\$errors) !!}</section>

    <section class=\"column is-12 padding-0\">

    {!! Form::open( ['url'=> action('$controller@store'), 'enctype'=>'multipart/form-data', 'class'=> 'columns is-multiline' ]) !!}

        ";
        
        return $data;
        
    }
    
    
    private function view_create_end()
    {
        
        $model = $this->model;
        
        $data = "
        <div class=\"field is-horizontal column is-12\">
            <div class=\"field-body\">
                <div class=\"field\">
                    <div class=\"control has-text-centered\">
                        <button class=\"button is-info\" type=\"submit\">Save</button>
                    </div>
                </div>
            </div>
        </div>
    
    {!! Form::close() !!}


    </section>
</main>
@stop
        ";
        
        return $data;
        
    }
    
    
    private function view_create_form_elements()
    {
        
        $data = "";
        
        foreach( (array) $this->columns as $column)
        {
        
            if($column != 'created_at' && $column != 'updated_at' && $column != 'id' && $column != 'created_by' && $column != 'updated_by' && ! ends_with($column, '_link') )
            {
                
                if( ends_with($column, '_id') )
                {
                    
                    $belongsTo = ucfirst(substr($column, 0, -3));
                    
                    $select2 = $column == 'user_id' ? 'user-search' : 'select2';
                    
                    $select2 = $column == 'product_id' ? 'product-search' : 'select2';
                    
                    $data .= "
        <div class=\"field has-addons column is-6-desktop is-12-mobile\">
            <div class=\"control\">
                <button type=\"button\" class=\"button is-info\">".str_replace('_',' ',ucfirst($column))."</button>
            </div>
            <div class=\"control is-expanded\">
                <div class=\"select is-fullwidth\">
                    {!! Form::select('$column', \App\\$belongsTo::orderBy('name')->take(100)->get()->pluck('name', 'id')->toArray(), old('$column') , ['class'=>'select2', 'aria-describedby'=> '$column' ]) !!}
                </div>
            </div>
        </div>
        
                ";
                    
                } elseif(substr($column, 0, 3) == 'is_')
                {
                    
                $data .= "
        <div class=\"field has-addons column is-6-desktop is-12-mobile\">
            <div class=\"control\">
                <button type=\"button\" class=\"button is-info\">".ucfirst(str_replace('_',' ',substr(ucfirst($column), 3)))."?</button>
            </div>
            <div class=\"control is-expanded\">
                <div class=\"select is-fullwidth\">
                    {!! Form::select('$column', [ ''=>'-Select-','1'=>'Yes', '0'=>'No'], old('$column')) !!}
                </div>
            </div>
        </div>
        
                ";
                
                } elseif(substr($column, -5) == '_date')
                {
                    
                $data .= "
                
        <div class=\"field has-addons column is-6-desktop is-12-mobile\">
            <div class=\"control\">
                <a class=\"button is-info\">
                ".str_replace('_',' ',substr(ucfirst($column), 0))."
                </a>
            </div>
            <div class=\"control is-expanded\">
                {!! Form::text('$column', old('$column') , ['class'=>'input datepicker', 'aria-describedby'=> '$column']) !!}
            </div>
        </div>
                
                ";
                
                } elseif(substr($column, -5) == '_time')
                {
                    
                $data .= "
        <div class=\"field has-addons column is-6-desktop is-12-mobile\">
            <div class=\"control\">
                <a class=\"button is-info\">
                ".str_replace('_',' ',substr(ucfirst($column), 0))."
                </a>
            </div>
            <div class=\"control is-expanded\">
                {!! Form::text('$column', old('$column') , ['class'=>'input timepicker']) !!}
            </div>
        </div>
                ";
                
                } elseif( ends_with($column, ['_photo', '_image', '_file'] ) )
                {
                
                $file_column = $column."s";
                $data .= "
        <div class=\"field has-addons column is-6-desktop is-12-mobile\">
            <div class=\"control\">
                <a class=\"button is-info\">
                ".str_replace('_',' ',substr(ucfirst($column), 0))."
                </a>
            </div>
            <div class=\"control is-expanded\">
                {!! Form::file('$file_column', ['class'=>'file']) !!}
            </div>
        </div>
        
                ";
                
                } elseif( ends_with($column, ['_images', '_files']) )
                {
                
                $file_column = substr($column, 0, -1);
                $data .= "
        <div class=\"field has-addons column is-6-desktop is-12-mobile\">
            <div class=\"control\">
                <a class=\"button is-info\">
                ".str_replace('_',' ',ucfirst($column))."
                </a>
            </div>
            <div class=\"control is-expanded\">
                {!! Form::file('".$file_column."[]', ['class'=>'file', 'multiple'=>'multiple']) !!}
            </div>
        </div>
                ";
                
                } elseif( ends_with($column, ['_details', '_detail', '_description']) )
                {
            $data .= "
        <div class=\"field column is-12\">
            <div class=\"control\">
                <a class=\"button is-info\">
                ".str_replace('_',' ',ucfirst($column))."
                </a>
            </div>
            <div class=\"control is-expanded\">
                {!! Form::textarea('$column', old('$column') , ['class'=>'textarea summernote']) !!}
            </div>
        </div>
                ";
                } else{
                    
                $data .= "
        <div class=\"field has-addons column is-6-desktop is-12-mobile\">
            <div class=\"control\">
                <a class=\"button is-info\">
                ".str_replace('_',' ',ucfirst($column))."
                </a>
            </div>
            <div class=\"control is-expanded\">
                {!! Form::text('$column', old('$column') , ['class'=>'input', 'aria-describedby'=> '$column']) !!}
            </div>
        </div>
                ";
                
                } 
                
                
            }
            
        }
        
        return $data;
        
    }
    
}