<?php

namespace App\Http\Traits\Parsers;

Trait ViewShow
{
    
    public function view_show()
    {
        
        $start_time = microtime(true);
        
        $table = $this->table;
        
        
        $data    = "";
        
        $data   .= $this->view_show_start();
        
        $data   .= $this->view_show_errors();
        
        $data   .= $this->view_show_edit_button();
        
        $data   .= $this->view_show_list_table();
        
        $data   .= $this->view_show_end();
        
        
        file_write(base_path().'/resources/views/admin/'.$table.'/show.blade.php', $data);
        
        $end_time = microtime(true);
        
        return "show created in ". ($end_time - $start_time);
        
    }
    
    
    private function view_show_start()
    {
        
        $table      = $this->table;
        
        $model      = $this->model;
        
        $controller = $this->controller;
        
        
        $data ="@extends('admin.layout')

@section('title')".str_replace('_',' ',$model)." - {{ settings()->application_name }} @stop

@section('main')

<main class=\"column is-12-desktop is-12-mobile padding-top-10 padding-bottom-20 columns is-multiline\" >

    
    <!--Generated by Functions-->
    <section class=\"column is-12 padding-0\">{!! breadcrumb('$controller') !!}</section>
    
    <section class=\"column is-12 padding-0\">

        <h1 class=\"title is-3\">".str_replace('_',' ',$model)."</h1>

    </section>

";
        
        
        return $data;
        
    }
    
    
    private function view_show_end()
    {
        
        $data = "</main>\n\n@stop";
        
        return $data;
        
    }
    
    
    private function view_show_errors()
    {
        
        $data = "
    <section class=\"column is-12 padding-0\">{!! errors(\$errors) !!}</section>
    ";
        
        return $data;
        
    }
    
    
    private function view_show_edit_button()
    {
        
        $controller = $this->controller;
        
        $instance = '$'.str_singular( strtolower( $this->model ) );
        
        $data = "
    <section class=\"column is-12 padding-0 has-text-right blue-text\">
        
        <a href=\"{{action('$controller@edit', ".$instance."->id)}}\" class=\"is-link\">Edit ".str_singular( strtolower( $this->model ) )."</a>
    
    </section>
        ";
        
        return $data;
        
    }
    
    
    private function view_show_list_table()
    {
        
        $columns    = $this->columns;
        
        $controller = $this->controller;
        
        $table      = $this->table;
        
        $instance   = '$'.str_singular( strtolower( $table ) );
        
        
        $show = "
    @if( $instance )
    <section class=\"column is-12 padding-0\">
        <table class=\"table table-bordered table-striped\">
            <tdead>
                <tr>
                    <td width=\"200\" class=\"font-weight-700\">Title</td>
                    <td class=\"font-weight-700\">Details</td>
                </tr>
            </tdead>
            <tbody>";
            
            foreach( (array) $columns as $column)
            {
                
                if( ends_with($column, '_id') )
                {
                    $belongsTo = substr($column, 0, count($column) -4);
                    $show .= "
                    <tr>
                        <td>". ucfirst( substr( $column, 0, -3 ) ) ."</td>
                        <td>{{ ".$instance."->".$belongsTo." ? ".$instance."->".$belongsTo."->name : '' }}</td>
                    </tr>
                    ";
                    
                } elseif(substr($column, -6) == '_photo' || substr($column, -5) == '_file'){
            
                    $show .= "
                    <tr>
                        <td>".str_replace('_',' ',ucfirst($column))."</td>
                        <td>
                            @if( strlen( $instance->$column ) > 5 )
                            <a href=\"{{ $instance->$column }}\" class=\"btn btn-default btn-rounded btn-xs\"><span class=\"fa fa-download\"></span></a>
                            @else
                            None
                            @endif
                        </td>
                    </tr>
                    ";
                    
                } elseif(substr($column, -7) == '_images'){
            
                    $show .= "
                    <tr>
                        <td>".str_replace('_',' ',ucfirst($column))."</td>
                        <td>
                        @if( is_array( $instance->column ) && count( $instance->column ) > 0)
                        <div class=\"gallery\">
                        @foreach( $instance->column  as \$image)
                        <a class=\"gallery-item\" href=\"{{\$image}}\" title=\"Image\" data-gallery>
                            <div class=\"image\">
                                {!! xs(\$image) !!}
                            </div>
                        </a>
                        @endforeach
                        </div>
                        @endif
                        </td>
                    </tr>
                    ";
                    
                } elseif(substr($column, -6) == '_files'){
            
                    $show .= "
                    <tr>
                        <td>".str_replace('_',' ',ucfirst($column))."</td>
                        <td>
                        @if( is_array( $instance->$column ) && count( $instance->$column ) > 0)
                        <ul class=\"list-group\">
                        @foreach( $instance->$column as \$file)
                        <li class=\"list-group-item\" >
                            <a class=\"btn btn-primary\" href=\"{{\$file}}\" title=\"\$file\" >{{\$file}}</a>
                        </li>
                        @endforeach
                        </ul>
                        @endif
                        </td>
                    </tr>
                    ";
                    
                } elseif( $column == 'created_by'){
                    
                    $show .= "
                    <tr>
                        <td>Created By</td>
                        <td>{{ $instance->createdBy ? $instance->createdBy->name : '' }}</td>
                    </tr>
                    ";
                    
                } elseif( $column == 'updated_by'){
                    
                    $show .= "
                    <tr>
                        <td>Updated By</td>
                        <td>{{ $instance->updatedBy ? $instance->updatedBy->name : '' }}</td>
                    </tr>
                    ";
                    
                } else{
            
                    $show .= "
                    <tr>
                        <td>".str_replace('_',' ',ucfirst($column))."</td>
                        <td>{{ $instance->$column }}</td>
                    </tr>
                    ";
                    
                }
                
            }
            
            $show .="
                <tr>
                    <td>
                        {!! edits('$controller', ".$instance."->id, 'edit', ['class'=>'button is-warning is-small']) !!}
                ";
                
            
            $show .="                
                    </td>
                    <td>
                        {!! deletes('$controller', ".$instance."->id, '<span class=\'fa fa-times\'></span>', ['class'=>'button is-danger is-small']) !!}
                    </td>
                </tr>
            </tbody>
        </table>
    </section>
    @endif
        ";
        
        return $show;
        
    }
    
}